import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import 'package:tactical_app/features/auth/models/login_request_model.dart';
import 'package:tactical_app/features/auth/models/login_response_model.dart';

part 'auth_rest_client.g.dart';

/// Retrofit API interface for authentication endpoints.
///
/// The implementation is auto-generated by `retrofit_generator`.
/// Run `dart run build_runner build` to generate the `.g.dart` file.
///
/// The [Dio] instance injected here already includes:
/// - Bearer token interceptor (from [DioClient])
/// - [Chuck] interceptor for in-app HTTP traffic inspection
/// - [LogInterceptor] for debug logging
@RestApi()
abstract class AuthRestClient {
  factory AuthRestClient(Dio dio, {String baseUrl}) = _AuthRestClient;

  /// Authenticate with email and password.
  /// Returns a strongly-typed [LoginResponseModel].
  @POST('/auth/login')
  Future<LoginResponseModel> login(@Body() LoginRequestModel request);
}
